#!/usr/bin/env python3
"""
Claude 4.5 vs Ollama GUTT Decomposition - Side-by-Side Comparison

Shows each of the 9 hero prompts with actual GUTT decompositions from both models.
"""

import json
from pathlib import Path
from textwrap import wrap

def load_gutt_file(filepath):
    """Load GUTT decomposition from JSON file."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except:
        return None

def print_side_by_side_comparison():
    """Print side-by-side comparison of Claude vs Ollama GUTT decompositions."""
    
    prompts = [
        ("organizer-1", "Calendar Prioritization", "Keep my Calendar up to date by committing to only meetings that are part of my priorities."),
        ("organizer-2", "Meeting Prep Tracking", "Track all my important meetings and flag any that require focus time to prepare for them."),
        ("organizer-3", "Time Reclamation", "Help me understand where I am spending my time and identify ways I can reclaim time to focus more on my top priorities."),
        ("schedule-1", "Recurring 1:1 Scheduling", "Starting next week, I want a weekly 30-min 1:1 with {name}. Afternoons preferred, avoid Fridays. Automatically reschedule on declines or conflicts."),
        ("schedule-2", "Block Time & Reschedule", "Clear my Thursday afternoon. Update my RSVPs and help me reschedule my meetings to another time and show me as {status}."),
        ("schedule-3", "Multi-Person Scheduling", "Land a time to meet about Project Alpha with Chris, Sangya, and Kat for 1 hour in the next 2 weeks. Schedule over 1:1s and lunches if needed and work around Kat's schedule. Make the meeting in person and add a room."),
        ("collaborate-1", "Agenda Creation", "Help me set the agenda to review the progress of Project Alpha with the product and marketing team to get confirmation we are on track and discuss any blocking issues or risks."),
        ("collaborate-2", "Executive Briefing Prep", "Review the materials for my meeting with senior leadership and suggest the best way to summarize the topics into three main discussion points. Generate any objections or concerns that might come up and give me effective responses."),
        ("collaborate-3", "Customer Meeting Prep", "Prepare a brief for my upcoming meeting with customer Beta and include a dossier for each customer attendee and the topics they are most interested in. Include a background on their company.")
    ]
    
    analysis_dir = Path('hero_prompt_analysis')
    
    print("\n" + "=" * 140)
    print("CLAUDE SONNET 4.5 vs OLLAMA (gpt-oss:20b) - GUTT DECOMPOSITION COMPARISON")
    print("=" * 140)
    print("\nNote: Showing actual GUTT decompositions generated by each model")
    print("=" * 140)
    
    for prompt_id, prompt_name, prompt_text in prompts:
        # Load both decompositions
        claude_file = analysis_dir / f"claude_gutt_{prompt_id}.json"
        ollama_file = analysis_dir / f"ollama_gutt_{prompt_id}.json"
        
        claude_data = load_gutt_file(claude_file)
        ollama_data = load_gutt_file(ollama_file)
        
        if not claude_data or not ollama_data:
            print(f"\n⚠️  Skipping {prompt_id} - missing data files")
            continue
        
        claude_gutts = claude_data.get('gutts', [])
        ollama_gutts = ollama_data.get('gutts', [])
        
        # Print prompt header
        print(f"\n{'─' * 140}")
        print(f"PROMPT {prompt_id.upper()}: {prompt_name}")
        print(f"{'─' * 140}")
        
        # Wrap prompt text to fit
        wrapped_prompt = wrap(prompt_text, width=136)
        for line in wrapped_prompt:
            print(f"  {line}")
        
        print(f"\n  CLAUDE GUTTS: {len(claude_gutts)}                                    OLLAMA GUTTS: {len(ollama_gutts)}")
        print(f"  {'─' * 68}{'─' * 68}")
        
        # Print GUTTs side by side
        max_gutts = max(len(claude_gutts), len(ollama_gutts))
        
        for i in range(max_gutts):
            claude_name = claude_gutts[i].get('name', '') if i < len(claude_gutts) else ''
            ollama_name = ollama_gutts[i].get('name', '') if i < len(ollama_gutts) else ''
            
            # Truncate if too long
            if len(claude_name) > 60:
                claude_name = claude_name[:57] + "..."
            if len(ollama_name) > 60:
                ollama_name = ollama_name[:57] + "..."
            
            claude_display = f"{i+1}. {claude_name}" if claude_name else ""
            ollama_display = f"{i+1}. {ollama_name}" if ollama_name else ""
            
            print(f"  {claude_display:<68}{ollama_display:<68}")
    
    print(f"\n{'=' * 140}\n")

def print_summary_table():
    """Print summary statistics table."""
    
    prompts_info = [
        ("organizer-1", "Calendar Prioritization"),
        ("organizer-2", "Meeting Prep Tracking"),
        ("organizer-3", "Time Reclamation"),
        ("schedule-1", "Recurring 1:1 Scheduling"),
        ("schedule-2", "Block Time & Reschedule"),
        ("schedule-3", "Multi-Person Scheduling"),
        ("collaborate-1", "Agenda Creation"),
        ("collaborate-2", "Executive Briefing Prep"),
        ("collaborate-3", "Customer Meeting Prep")
    ]
    
    analysis_dir = Path('hero_prompt_analysis')
    
    print("\n" + "=" * 100)
    print("SUMMARY TABLE")
    print("=" * 100)
    print(f"\n{'Prompt ID':<20} {'Prompt Name':<30} {'Claude':>10} {'Ollama':>10} {'Difference':>10}")
    print("-" * 100)
    
    total_claude = 0
    total_ollama = 0
    
    for prompt_id, prompt_name in prompts_info:
        claude_file = analysis_dir / f"claude_gutt_{prompt_id}.json"
        ollama_file = analysis_dir / f"ollama_gutt_{prompt_id}.json"
        
        claude_data = load_gutt_file(claude_file)
        ollama_data = load_gutt_file(ollama_file)
        
        claude_count = len(claude_data.get('gutts', [])) if claude_data else 0
        ollama_count = len(ollama_data.get('gutts', [])) if ollama_data else 0
        diff = claude_count - ollama_count
        
        total_claude += claude_count
        total_ollama += ollama_count
        
        print(f"{prompt_id:<20} {prompt_name:<30} {claude_count:>10} {ollama_count:>10} {diff:>+10}")
    
    print("-" * 100)
    total_diff = total_claude - total_ollama
    print(f"{'TOTALS':<20} {'':<30} {total_claude:>10} {total_ollama:>10} {total_diff:>+10}")
    print()
    print(f"Average GUTTs per prompt:        Claude: {total_claude/9:.1f}        Ollama: {total_ollama/9:.1f}")
    print(f"Ollama generates {(1 - total_ollama/total_claude)*100:.1f}% fewer GUTTs than Claude")
    print()

if __name__ == "__main__":
    print_summary_table()
    print_side_by_side_comparison()
